services:
  mysql:
    image: mariadb
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=heroquest
      - MYSQL_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://admin:password@dbserver/heroquest
    volumes:
      - ./app:/home/heroquest/app:ro
    depends_on:
      - mysql
    links:
      - mysql:dbserver
