services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=heroquest
      - MYSQL_PASSWORD=password
      - MYSQL_USER=admin
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_COLLATION=utf8mb4_bin
      - TZ=Europe/Zurich
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./flask_app/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - TZ=Europe/Zurich

  flask:
    image: hoganton/heroquest_assistant:latest
    container_name: flask
    restart: always
    volumes:
      - ./flask_app/app:/home/heroquest/app:ro
    depends_on:
      - mariadb
    environment:
      - TZ=Europe/Zurich
