"""empty message

Revision ID: b2ace49c23a7
Revises: 59eb7db512ab
Create Date: 2023-08-27 19:42:48.184897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2ace49c23a7'
down_revision = '59eb7db512ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hero',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=True),
    sa.Column('character', sa.String(length=140), nullable=True),
    sa.Column('attack_dice', sa.Integer(), nullable=True),
    sa.Column('defend_dice', sa.Integer(), nullable=True),
    sa.Column('starting_body_points', sa.Integer(), nullable=True),
    sa.Column('starting_mind_points', sa.Integer(), nullable=True),
    sa.Column('weapons', sa.String(length=140), nullable=True),
    sa.Column('armor', sa.String(length=140), nullable=True),
    sa.Column('body_points', sa.Integer(), nullable=True),
    sa.Column('quests', sa.Integer(), nullable=True),
    sa.Column('gold_coins', sa.Integer(), nullable=True),
    sa.Column('items', sa.String(length=560), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index('ix_post_timestamp')

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.VARCHAR(length=140), nullable=True))

    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('body', sa.VARCHAR(length=140), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index('ix_post_timestamp', ['timestamp'], unique=False)

    op.drop_table('hero')
    # ### end Alembic commands ###
