name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ github.repository }}:${{ github.sha }} .

      - name: Set environment variables
        run: |
          echo "IMAGE_NAME=${{ github.repository }}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${{ github.event.release.tag_name }}" >> $GITHUB_ENV

      - name: Tag Docker image with release/tag and latest
        run: |
          docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:$IMAGE_TAG
          docker tag $IMAGE_NAME:$GITHUB_SHA $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:$IMAGE_TAG
          docker push $IMAGE_NAME:latest

  deploy_on_azure:
    name: Run Ansible
    runs-on: ubuntu-latest
    needs: push_to_registry
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Install ssh-agent if not already installed
        run: command -v ssh-agent >/dev/null || ( apt update -y && apt install openssh-client -y )

      - name: Set Private Key
        run: echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

      - name: Create the SSH directory and give it the right permissions
        run: mkdir -p ~/.ssh && chmod 700 ~/.ssh

      - name: Add the gitlab ssh-host-key
        run: ssh-keyscan $AZURE_SERVER_HOST >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts

      - name: Add the gitlab ssh-host-key
        run: ssh-keyscan $AZURE_SERVER_HOST >> ~/.ssh/known_hosts && chmod 644 ~/.ssh/known_hosts

      - name: Run Docker Compose pull
        run: |
          ssh $USERNAME_AZURE@$AZURE_SERVER_HOST "docker-compose -f /home/vega/project/heroquest_assistant/docker-compose.yml pull"
